// Nigerian Tertiary Institutions - Full Database
// Includes popular student nicknames/abbreviations used on campus
// 1279 institutions: Universities, Polytechnics, Colleges

const INSTITUTIONS = [
  // ─── FEDERAL UNIVERSITIES ───────────────────────────────────────────────────
  { name: "Abubakar Tafawa Balewa University, Bauchi", nickname: "ATBU", type: "University", state: "Bauchi" },
  { name: "Ahmadu Bello University, Zaria", nickname: "ABU Zaria", type: "University", state: "Kaduna" },
  { name: "Alex Ekwueme Federal University, Ndufu-Alike", nickname: "FUNAI", type: "University", state: "Ebonyi" },
  { name: "Bayero University, Kano", nickname: "BUK", type: "University", state: "Kano" },
  { name: "Federal University of Agriculture, Abeokuta", nickname: "FUNAAB", type: "University", state: "Ogun" },
  { name: "Federal University of Agriculture, Bassambiri", nickname: "FUAB", type: "University", state: "Bayelsa" },
  { name: "Federal University of Agriculture, Mubi", nickname: "FUAM", type: "University", state: "Adamawa" },
  { name: "Federal University of Agriculture, Zuru", nickname: "FUAZ", type: "University", state: "Kebbi" },
  { name: "Federal University of Petroleum Resources, Effurun", nickname: "FUPRE", type: "University", state: "Delta" },
  { name: "Federal University of Technology, Akure", nickname: "FUTA", type: "University", state: "Ondo" },
  { name: "Federal University of Technology, Minna", nickname: "FUTMINNA", type: "University", state: "Niger" },
  { name: "Federal University of Technology, Owerri", nickname: "FUTO", type: "University", state: "Imo" },
  { name: "Federal University, Birnin-Kebbi", nickname: "FUBK", type: "University", state: "Kebbi" },
  { name: "Federal University, Dutse", nickname: "FUD", type: "University", state: "Jigawa" },
  { name: "Federal University, Dutsin-Ma", nickname: "FUDMA", type: "University", state: "Katsina" },
  { name: "Federal University, Gashua", nickname: "FUGASHUA", type: "University", state: "Yobe" },
  { name: "Federal University, Gusau", nickname: "FUG", type: "University", state: "Zamfara" },
  { name: "Federal University, Kashere", nickname: "FUKASHERE", type: "University", state: "Gombe" },
  { name: "Federal University, Lafia", nickname: "FULAFIA", type: "University", state: "Nasarawa" },
  { name: "Federal University, Lokoja", nickname: "FULOKOJA", type: "University", state: "Kogi" },
  { name: "Federal University, Otuoke", nickname: "FUOTUOKE", type: "University", state: "Bayelsa" },
  { name: "Federal University, Oye-Ekiti", nickname: "FUOYE", type: "University", state: "Ekiti" },
  { name: "Federal University, Wukari", nickname: "FUWUKARI", type: "University", state: "Taraba" },
  { name: "Michael Okpara University of Agriculture, Umudike", nickname: "MOUAU", type: "University", state: "Abia" },
  { name: "Modibbo Adama University, Yola", nickname: "MAUTECH", type: "University", state: "Adamawa" },
  { name: "National Open University of Nigeria", nickname: "NOUN", type: "University", state: "Lagos" },
  { name: "Nnamdi Azikiwe University, Awka", nickname: "UNIZIK", type: "University", state: "Anambra" },
  { name: "Obafemi Awolowo University, Ile-Ife", nickname: "OAU / Great Ife", type: "University", state: "Osun" },
  { name: "University of Abuja", nickname: "UNIABUJA", type: "University", state: "FCT" },
  { name: "University of Benin", nickname: "UNIBEN", type: "University", state: "Edo" },
  { name: "University of Calabar", nickname: "UNICAL", type: "University", state: "Cross River" },
  { name: "University of Ibadan", nickname: "UI", type: "University", state: "Oyo" },
  { name: "University of Ilorin", nickname: "UNILORIN", type: "University", state: "Kwara" },
  { name: "University of Jos", nickname: "UNIJOS", type: "University", state: "Plateau" },
  { name: "University of Lagos", nickname: "UNILAG / Lag", type: "University", state: "Lagos" },
  { name: "University of Maiduguri", nickname: "UNIMAID", type: "University", state: "Borno" },
  { name: "University of Port Harcourt", nickname: "UNIPORT", type: "University", state: "Rivers" },
  { name: "University of Uyo", nickname: "UNIUYO", type: "University", state: "Akwa Ibom" },
  { name: "Usmanu Danfodiyo University, Sokoto", nickname: "UDUSOK", type: "University", state: "Sokoto" },
  { name: "Federal University of Technology, Babura", nickname: "FUTB", type: "University", state: "Jigawa" },
  { name: "Federal University of Technology, Ikot-Abasi", nickname: "FUTIA", type: "University", state: "Akwa Ibom" },
  { name: "Federal University of Agriculture and Technology, Okeho", nickname: "FUATO", type: "University", state: "Oyo" },
  { name: "Federal University of Agriculture and Development Studies, Iragbiji", nickname: "FUADS", type: "University", state: "Osun" },

  // ─── STATE UNIVERSITIES ──────────────────────────────────────────────────────
  { name: "Abia State University, Uturu", nickname: "ABSU", type: "University", state: "Abia" },
  { name: "Achievers University, Owo", nickname: "AU Owo", type: "University", state: "Ondo" },
  { name: "Adamawa State University, Mubi", nickname: "ADSU", type: "University", state: "Adamawa" },
  { name: "Adekunle Ajasin University, Akungba-Akoko", nickname: "AAUA", type: "University", state: "Ondo" },
  { name: "Adeleke University, Ede", nickname: "AU Ede", type: "University", state: "Osun" },
  { name: "Afe Babalola University, Ado-Ekiti", nickname: "ABUAD", type: "University", state: "Ekiti" },
  { name: "Ajayi Crowther University, Oyo", nickname: "ACU", type: "University", state: "Oyo" },
  { name: "Akwa Ibom State University", nickname: "AKSU", type: "University", state: "Akwa Ibom" },
  { name: "Al-Hikmah University, Ilorin", nickname: "Al-Hikmah", type: "University", state: "Kwara" },
  { name: "Ambrose Alli University, Ekpoma", nickname: "AAU Ekpoma", type: "University", state: "Edo" },
  { name: "American University of Nigeria, Yola", nickname: "AUN", type: "University", state: "Adamawa" },
  { name: "Anchor University, Ayobo", nickname: "AUI", type: "University", state: "Lagos" },
  { name: "Atiba University, Oyo", nickname: "Atiba", type: "University", state: "Oyo" },
  { name: "Augustine University, Ilara, Lagos", nickname: "AUL", type: "University", state: "Lagos" },
  { name: "Babcock University, Ilishan-Remo", nickname: "Babcock", type: "University", state: "Ogun" },
  { name: "Bauchi State University, Gadau", nickname: "BASU", type: "University", state: "Bauchi" },
  { name: "Bayelsa Medical University, Yenagoa", nickname: "BMU", type: "University", state: "Bayelsa" },
  { name: "Bells University of Technology, Ota", nickname: "Bells Uni", type: "University", state: "Ogun" },
  { name: "Benson Idahosa University, Benin City", nickname: "BIU", type: "University", state: "Edo" },
  { name: "Benue State University, Makurdi", nickname: "BSU Makurdi", type: "University", state: "Benue" },
  { name: "Bingham University, Karu", nickname: "Bingham", type: "University", state: "Nasarawa" },
  { name: "Borno State University, Maiduguri", nickname: "BOSU", type: "University", state: "Borno" },
  { name: "Bowen University, Iwo", nickname: "Bowen", type: "University", state: "Osun" },
  { name: "Caleb University, Imota", nickname: "Caleb Uni", type: "University", state: "Lagos" },
  { name: "Caritas University, Enugu", nickname: "Caritas", type: "University", state: "Enugu" },
  { name: "Chukwuemeka Odumegwu Ojukwu University, Uli", nickname: "COOU", type: "University", state: "Anambra" },
  { name: "Clifford University, Owerrintta", nickname: "Clifford", type: "University", state: "Abia" },
  { name: "Coal City University, Enugu", nickname: "CCU", type: "University", state: "Enugu" },
  { name: "Covenant University, Ota", nickname: "Covenant / CU", type: "University", state: "Ogun" },
  { name: "Crescent University, Abeokuta", nickname: "Crescent", type: "University", state: "Ogun" },
  { name: "Delta State University, Abraka", nickname: "DELSU", type: "University", state: "Delta" },
  { name: "Delta State University of Science and Technology, Ozoro", nickname: "DESTECH", type: "University", state: "Delta" },
  { name: "Dennis Osadebay University, Asaba", nickname: "DOU", type: "University", state: "Delta" },
  { name: "Ebonyi State University, Abakaliki", nickname: "EBSU", type: "University", state: "Ebonyi" },
  { name: "Edo University, Iyamho", nickname: "EU Iyamho", type: "University", state: "Edo" },
  { name: "Edwin Clark University, Kiagbodo", nickname: "ECU", type: "University", state: "Delta" },
  { name: "Ekiti State University, Ado-Ekiti", nickname: "EKSU", type: "University", state: "Ekiti" },
  { name: "Elizade University, Ilara-Mokin", nickname: "Elizade", type: "University", state: "Ondo" },
  { name: "Enugu State University of Science and Technology", nickname: "ESUT", type: "University", state: "Enugu" },
  { name: "Fountain University, Osogbo", nickname: "FUI", type: "University", state: "Osun" },
  { name: "Gombe State University, Gombe", nickname: "GSU", type: "University", state: "Gombe" },
  { name: "Godfrey Okoye University, Enugu", nickname: "GO Uni", type: "University", state: "Enugu" },
  { name: "Greenfield University, Kaduna", nickname: "GreenField", type: "University", state: "Kaduna" },
  { name: "Hallmark University, Ijebu-Itele", nickname: "HU", type: "University", state: "Ogun" },
  { name: "Hezekiah University, Umudi", nickname: "Hezekiah", type: "University", state: "Imo" },
  { name: "Ibrahim Badamasi Babangida University, Lapai", nickname: "IBBU", type: "University", state: "Niger" },
  { name: "Igbinedion University, Okada", nickname: "IUO / Igbinedion", type: "University", state: "Edo" },
  { name: "Ignatius Ajuru University of Education, Port Harcourt", nickname: "IAUE", type: "University", state: "Rivers" },
  { name: "Imo State University, Owerri", nickname: "IMSU", type: "University", state: "Imo" },
  { name: "Joseph Ayo Babalola University, Ikeji-Arakeji", nickname: "JABU", type: "University", state: "Osun" },
  { name: "Joseph Sarwuan Tarka University, Makurdi", nickname: "JOSTUM", type: "University", state: "Benue" },
  { name: "Kaduna State University", nickname: "KASU", type: "University", state: "Kaduna" },
  { name: "Kano University of Science and Technology, Wudil", nickname: "KUST Wudil", type: "University", state: "Kano" },
  { name: "Kings University, Ode-Omu", nickname: "Kings Uni", type: "University", state: "Osun" },
  { name: "Kogi State University, Kabba", nickname: "KSU Kabba", type: "University", state: "Kogi" },
  { name: "Kwara State University, Malete", nickname: "KWASU", type: "University", state: "Kwara" },
  { name: "Kwararafa University, Wukari", nickname: "Kwararafa", type: "University", state: "Taraba" },
  { name: "Ladoke Akintola University of Technology, Ogbomoso", nickname: "LAUTECH", type: "University", state: "Oyo" },
  { name: "Lagos State University, Ojo", nickname: "LASU", type: "University", state: "Lagos" },
  { name: "Lagos State University of Science and Technology, Ikorodu", nickname: "LASUSTECH", type: "University", state: "Lagos" },
  { name: "Landmark University, Omu-Aran", nickname: "LMU", type: "University", state: "Kwara" },
  { name: "Lead City University, Ibadan", nickname: "LCU", type: "University", state: "Oyo" },
  { name: "Madonna University, Elele", nickname: "Madonna", type: "University", state: "Rivers" },
  { name: "Mountain Top University, Ogun", nickname: "MTU", type: "University", state: "Ogun" },
  { name: "McPherson University, Seriki Sotayo", nickname: "McPherson", type: "University", state: "Ogun" },
  { name: "Nasarawa State University, Keffi", nickname: "NSUK", type: "University", state: "Nasarawa" },
  { name: "Niger Delta University, Wilberforce Island", nickname: "NDU", type: "University", state: "Bayelsa" },
  { name: "Nigerian Army University, Biu", nickname: "NAU Biu", type: "University", state: "Borno" },
  { name: "Nile University of Nigeria, Abuja", nickname: "Nile Uni", type: "University", state: "FCT" },
  { name: "Novena University, Ogume", nickname: "Novena", type: "University", state: "Delta" },
  { name: "Obong University, Akwa Ibom", nickname: "OBONG", type: "University", state: "Akwa Ibom" },
  { name: "Olabisi Onabanjo University, Ago-Iwoye", nickname: "OOU", type: "University", state: "Ogun" },
  { name: "Osun State University, Osogbo", nickname: "UNIOSUN", type: "University", state: "Osun" },
  { name: "Pan-Atlantic University, Ibeju-Lekki", nickname: "PAU / LBS", type: "University", state: "Lagos" },
  { name: "Plateau State University, Bokkos", nickname: "PLASU", type: "University", state: "Plateau" },
  { name: "Prince Abubakar Audu University, Anyigba", nickname: "KOGI State Uni / KSU", type: "University", state: "Kogi" },
  { name: "Redeemers University, Ede", nickname: "RUN", type: "University", state: "Osun" },
  { name: "Rivers State University, Port Harcourt", nickname: "RSU", type: "University", state: "Rivers" },
  { name: "Salem University, Lokoja", nickname: "Salem", type: "University", state: "Kogi" },
  { name: "Skyline University Nigeria, Kano", nickname: "SUN", type: "University", state: "Kano" },
  { name: "Sokoto State University", nickname: "SSU", type: "University", state: "Sokoto" },
  { name: "Sule Lamido University, Kafin Hausa", nickname: "SLU", type: "University", state: "Jigawa" },
  { name: "Tai Solarin University of Education, Ijagun", nickname: "TASUED", type: "University", state: "Ogun" },
  { name: "Taraba State University, Jalingo", nickname: "TSU", type: "University", state: "Taraba" },
  { name: "Thomas Adewumi University, Oko-Irese", nickname: "TAU", type: "University", state: "Kwara" },
  { name: "Tansian University, Oba", nickname: "TANSIAN", type: "University", state: "Anambra" },
  { name: "Umaru Musa Yaradua University, Katsina", nickname: "UMYU", type: "University", state: "Katsina" },
  { name: "University of Africa, Toru-Orua", nickname: "UNIAF", type: "University", state: "Bayelsa" },
  { name: "University of Cross River State, Calabar", nickname: "UNICROSS", type: "University", state: "Cross River" },
  { name: "University of Delta, Agbor", nickname: "UNIDEL", type: "University", state: "Delta" },
  { name: "University of Mkar, Gboko", nickname: "UNIMKAR", type: "University", state: "Benue" },
  { name: "University of Nigeria, Nsukka", nickname: "UNN", type: "University", state: "Enugu" },
  { name: "University of Port-Harcourt", nickname: "UNIPORT", type: "University", state: "Rivers" },
  { name: "Veritas University, Abuja", nickname: "Veritas", type: "University", state: "FCT" },
  { name: "Wellspring University, Benin City", nickname: "Wellspring", type: "University", state: "Edo" },
  { name: "Wesley University, Ondo", nickname: "Wesley", type: "University", state: "Ondo" },
  { name: "Western Delta University, Oghara", nickname: "WDU", type: "University", state: "Delta" },
  { name: "Wigwe University, Isiokpo", nickname: "Wigwe", type: "University", state: "Rivers" },
  { name: "Yobe State University, Damaturu", nickname: "YSU", type: "University", state: "Yobe" },
  { name: "Zamfara State University", nickname: "ZASU", type: "University", state: "Zamfara" },
  { name: "Baze University, Abuja", nickname: "Baze", type: "University", state: "FCT" },
  { name: "Crawford University, Igbesa", nickname: "Crawford", type: "University", state: "Ogun" },
  { name: "Gregory University, Uturu", nickname: "GU Uturu", type: "University", state: "Abia" },
  { name: "Al-Qalam University, Katsina", nickname: "Al-Qalam", type: "University", state: "Katsina" },
  { name: "Achievers University, Owo", nickname: "AU", type: "University", state: "Ondo" },
  { name: "Dominican University, Ibadan", nickname: "Dominican", type: "University", state: "Oyo" },
  { name: "Rhema University, Aba", nickname: "Rhema", type: "University", state: "Abia" },
  { name: "Ritman University, Ikot-Ekpene", nickname: "Ritman", type: "University", state: "Akwa Ibom" },
  { name: "Paul University, Awka", nickname: "Paul Uni", type: "University", state: "Anambra" },
  { name: "Spiritan University, Nneochi", nickname: "Spiritan", type: "University", state: "Abia" },
  { name: "Topfaith University, Mkpatak", nickname: "Topfaith", type: "University", state: "Akwa Ibom" },
  { name: "Tansian University, Oba", nickname: "TANSIAN", type: "University", state: "Anambra" },
  { name: "Shanahan University, Onitsha", nickname: "Shanahan", type: "University", state: "Anambra" },
  { name: "Oduduwa University, Ipetumodu", nickname: "Oduduwa", type: "University", state: "Osun" },
  { name: "Christopher University, Mowe", nickname: "CU Mowe", type: "University", state: "Ogun" },
  { name: "Edwin Clark University, Kiagbodo", nickname: "ECU", type: "University", state: "Delta" },
  { name: "Hensard University, Toru Orua", nickname: "Hensard", type: "University", state: "Bayelsa" },
  { name: "Evangel University, Akaeze", nickname: "EU Akaeze", type: "University", state: "Ebonyi" },
  { name: "Claretian University, Nekede", nickname: "Claretian", type: "University", state: "Imo" },
  { name: "Karl Kumm University, Vom", nickname: "KKU", type: "University", state: "Plateau" },
  { name: "Precious Cornerstone University, Ibadan", nickname: "PCU", type: "University", state: "Oyo" },
  { name: "African University of Science and Technology, Abuja", nickname: "AUST", type: "University", state: "FCT" },
  { name: "Canadian University of Nigeria, Abuja", nickname: "CUNig", type: "University", state: "FCT" },
  { name: "European University of Nigeria, Abuja", nickname: "EUN", type: "University", state: "FCT" },
  { name: "Cosmopolitan University, Abuja", nickname: "CosmoUni", type: "University", state: "FCT" },
  { name: "Chrisland University, Owode", nickname: "Chrisland", type: "University", state: "Ogun" },
  { name: "Alvan Ikoku Federal University of Education, Owerri", nickname: "AIFCE / Alvan", type: "University", state: "Imo" },
  { name: "Adeyemi Federal University of Education, Ondo", nickname: "AFUED / Adeyemi", type: "University", state: "Ondo" },
  { name: "Emmanuel Alayande University of Education, Oyo", nickname: "EAUE", type: "University", state: "Oyo" },

  // ─── FEDERAL POLYTECHNICS ────────────────────────────────────────────────────
  { name: "Akanu Ibiam Federal Polytechnic, Unwana", nickname: "AIFP / Fed Poly Unwana", type: "Polytechnic", state: "Ebonyi" },
  { name: "Federal Polytechnic, Ado-Ekiti", nickname: "Fed Poly Ado", type: "Polytechnic", state: "Ekiti" },
  { name: "Federal Polytechnic, Bauchi", nickname: "Fed Poly Bauchi", type: "Polytechnic", state: "Bauchi" },
  { name: "Federal Polytechnic, Bida", nickname: "Fed Poly Bida", type: "Polytechnic", state: "Niger" },
  { name: "Federal Polytechnic, Damaturu", nickname: "Fed Poly Damaturu", type: "Polytechnic", state: "Yobe" },
  { name: "Federal Polytechnic, Daura", nickname: "Fed Poly Daura", type: "Polytechnic", state: "Katsina" },
  { name: "Federal Polytechnic, Ede", nickname: "Fed Poly Ede", type: "Polytechnic", state: "Osun" },
  { name: "Federal Polytechnic, Ekowe", nickname: "Fed Poly Ekowe", type: "Polytechnic", state: "Bayelsa" },
  { name: "Federal Polytechnic, Idah", nickname: "Fed Poly Idah", type: "Polytechnic", state: "Kogi" },
  { name: "Federal Polytechnic, Ilaro", nickname: "Fed Poly Ilaro / ILATECH", type: "Polytechnic", state: "Ogun" },
  { name: "Federal Polytechnic, Ile-Oluji", nickname: "Fed Poly Ile-Oluji", type: "Polytechnic", state: "Ondo" },
  { name: "Federal Polytechnic, Nasarawa", nickname: "Fed Poly Nasarawa / FEDPONAS", type: "Polytechnic", state: "Nasarawa" },
  { name: "Federal Polytechnic, Nekede", nickname: "Fed Poly Nekede / FEDPONEK", type: "Polytechnic", state: "Imo" },
  { name: "Federal Polytechnic, Offa", nickname: "Fed Poly Offa", type: "Polytechnic", state: "Kwara" },
  { name: "Federal Polytechnic, Oko", nickname: "Fed Poly Oko", type: "Polytechnic", state: "Anambra" },
  { name: "Federal Polytechnic, Kaltungo", nickname: "Fed Poly Kaltungo", type: "Polytechnic", state: "Gombe" },
  { name: "Federal Polytechnic, Mubi", nickname: "Fed Poly Mubi", type: "Polytechnic", state: "Adamawa" },
  { name: "Federal Polytechnic, Kabo", nickname: "Fed Poly Kabo", type: "Polytechnic", state: "Kano" },
  { name: "Federal Polytechnic, Wannune", nickname: "Fed Poly Wannune", type: "Polytechnic", state: "Benue" },
  { name: "Federal Polytechnic, Ohodo", nickname: "Fed Poly Ohodo", type: "Polytechnic", state: "Enugu" },
  { name: "Federal Polytechnic, Ukana", nickname: "Fed Poly Ukana", type: "Polytechnic", state: "Akwa Ibom" },
  { name: "Federal Polytechnic, Ugep", nickname: "Fed Poly Ugep", type: "Polytechnic", state: "Cross River" },
  { name: "Federal Polytechnic, Bali", nickname: "Fed Poly Bali", type: "Polytechnic", state: "Taraba" },
  { name: "Hussaini Adamu Federal Polytechnic, Kazaure", nickname: "HAFP / HAFEDPOLY", type: "Polytechnic", state: "Jigawa" },
  { name: "Waziri Umaru Federal Polytechnic, Birnin Kebbi", nickname: "WUFEB", type: "Polytechnic", state: "Kebbi" },
  { name: "Federal Polytechnic of Oil and Gas, Bonny", nickname: "FPOG Bonny", type: "Polytechnic", state: "Rivers" },
  { name: "Federal Polytechnic, Monguno", nickname: "Fed Poly Monguno", type: "Polytechnic", state: "Borno" },
  { name: "Federal Polytechnic, N'yak Shendam", nickname: "Fed Poly Shendam", type: "Polytechnic", state: "Plateau" },
  { name: "Federal Polytechnic, Isuochi", nickname: "Fed Poly Isuochi", type: "Polytechnic", state: "Abia" },
  { name: "Federal Polytechnic, Ayede-Ogo Oluwa", nickname: "Fed Poly Ayede", type: "Polytechnic", state: "Oyo" },
  { name: "Federal Polytechnic, Kaura Namoda", nickname: "Fed Poly Kaura Namoda", type: "Polytechnic", state: "Zamfara" },
  { name: "Federal Polytechnic, Orogun", nickname: "Fed Poly Orogun", type: "Polytechnic", state: "Delta" },

  // ─── STATE POLYTECHNICS ──────────────────────────────────────────────────────
  { name: "Abia State Polytechnic, Aba", nickname: "ABIAPOLY", type: "Polytechnic", state: "Abia" },
  { name: "Adamawa State Polytechnic, Yola", nickname: "Adamawa Poly", type: "Polytechnic", state: "Adamawa" },
  { name: "Akwa-Ibom State Polytechnic", nickname: "AKSPOLY", type: "Polytechnic", state: "Akwa Ibom" },
  { name: "Anambra State Polytechnic, Mgbakwu", nickname: "ANAPOLY", type: "Polytechnic", state: "Anambra" },
  { name: "Bayelsa State Polytechnic, Aleibiri", nickname: "Bayelsa Poly", type: "Polytechnic", state: "Bayelsa" },
  { name: "Benue State Polytechnic, Ugbokolo", nickname: "BENPOLY", type: "Polytechnic", state: "Benue" },
  { name: "Delta State Polytechnic, Ogwashi-Uku", nickname: "DESPO / Delta Poly Ogwashi", type: "Polytechnic", state: "Delta" },
  { name: "Delta State Polytechnic, Ozoro", nickname: "Delta Poly Ozoro", type: "Polytechnic", state: "Delta" },
  { name: "Delta State Polytechnic, Otefe", nickname: "Delta Poly Otefe", type: "Polytechnic", state: "Delta" },
  { name: "Edo State Polytechnic, Usen", nickname: "EDOPOLY", type: "Polytechnic", state: "Edo" },
  { name: "Ekiti State Polytechnic, Isan-Ekiti", nickname: "EKSPOLY", type: "Polytechnic", state: "Ekiti" },
  { name: "Enugu State Polytechnic, Iwollo", nickname: "ESPOLY", type: "Polytechnic", state: "Enugu" },
  { name: "Gombe State Polytechnic, Bajoga", nickname: "GSPOLY", type: "Polytechnic", state: "Gombe" },
  { name: "Imo State Polytechnic, Omuma", nickname: "IMOPOLY", type: "Polytechnic", state: "Imo" },
  { name: "Jigawa State Polytechnic, Dutse", nickname: "JIGSOPOLY", type: "Polytechnic", state: "Jigawa" },
  { name: "Kano State Polytechnic", nickname: "KANOPOLY", type: "Polytechnic", state: "Kano" },
  { name: "Kebbi State Polytechnic, Dakingari", nickname: "KEBPOLY", type: "Polytechnic", state: "Kebbi" },
  { name: "Kogi State Polytechnic, Lokoja", nickname: "KOGIPOLY", type: "Polytechnic", state: "Kogi" },
  { name: "Kwara State Polytechnic, Ilorin", nickname: "KWARAPOLY", type: "Polytechnic", state: "Kwara" },
  { name: "Lagos State Polytechnic, Ikorodu", nickname: "LASUPOLY / LASPOT", type: "Polytechnic", state: "Lagos" },
  { name: "Niger State Polytechnic, Zungeru", nickname: "NIGERPOLY", type: "Polytechnic", state: "Niger" },
  { name: "Osun State Polytechnic, Iree", nickname: "OSPOLY", type: "Polytechnic", state: "Osun" },
  { name: "Plateau State Polytechnic, Barkin-Ladi", nickname: "PLASSOPOLY", type: "Polytechnic", state: "Plateau" },
  { name: "Taraba State Polytechnic, Suntai", nickname: "TARPOLY", type: "Polytechnic", state: "Taraba" },

  // ─── PRIVATE POLYTECHNICS (notable ones) ──────────────────────────────────
  { name: "Auchi Polytechnic, Auchi", nickname: "AUCHI POLY", type: "Polytechnic", state: "Edo" },
  { name: "Kaduna Polytechnic, Kaduna", nickname: "KADPOLY", type: "Polytechnic", state: "Kaduna" },
  { name: "The Polytechnic, Ibadan", nickname: "POLYIBADAN", type: "Polytechnic", state: "Oyo" },
  { name: "Hassan Usman Katsina Polytechnic", nickname: "HUK Poly", type: "Polytechnic", state: "Katsina" },
  { name: "Nuhu Bamalli Polytechnic, Zaria", nickname: "NUHUPoly", type: "Polytechnic", state: "Kaduna" },
  { name: "Moshood Abiola Polytechnic, Abeokuta", nickname: "MAPOLY", type: "Polytechnic", state: "Ogun" },
  { name: "Yaba College of Technology, Yaba", nickname: "YABATECH", type: "Polytechnic", state: "Lagos" },
  { name: "Abraham Adesanya Polytechnic, Ijebu-Igbo", nickname: "AAPOLY", type: "Polytechnic", state: "Ogun" },
  { name: "Adeseun Ogundoyin Polytechnic, Eruwa", nickname: "ADE-OPE POLY", type: "Polytechnic", state: "Oyo" },
  { name: "The Polytechnic, Ile-Ife", nickname: "Poly Ife", type: "Polytechnic", state: "Osun" },
  { name: "Gateway ICT Polytechnic, Saapade", nickname: "GAPOSA", type: "Polytechnic", state: "Ogun" },
  { name: "Rufus Giwa Polytechnic, Owo", nickname: "RUGIPO", type: "Polytechnic", state: "Ondo" },
  { name: "Kenule Benson Saro-Wiwa Polytechnic, Bori", nickname: "KENPOLY", type: "Polytechnic", state: "Rivers" },
  { name: "Heritage Polytechnic, Ikot Udota", nickname: "HeritagePoly", type: "Polytechnic", state: "Akwa Ibom" },
  { name: "Kalac Christal Polytechnic, Lekki", nickname: "KALAC Poly", type: "Polytechnic", state: "Lagos" },
  { name: "Eastern Polytechnic, Port Harcourt", nickname: "EasternPoly PH", type: "Polytechnic", state: "Rivers" },
  { name: "Covenant Polytechnic, Aba", nickname: "CovPoly Aba", type: "Polytechnic", state: "Abia" },
  { name: "Ramat Polytechnic, Maiduguri", nickname: "RAMAPOLY", type: "Polytechnic", state: "Borno" },
  { name: "Abdu Gusau Polytechnic, Talata-Mafara", nickname: "AGPOLY", type: "Polytechnic", state: "Zamfara" },
  { name: "Allover Central Polytechnic, Ota", nickname: "AlloverPoly", type: "Polytechnic", state: "Ogun" },
  { name: "Port-Harcourt Polytechnic, Rumuola", nickname: "PHPoly", type: "Polytechnic", state: "Rivers" },
  { name: "D.S. Adegbenro ICT Polytechnic, Itori", nickname: "DSAP", type: "Polytechnic", state: "Ogun" },
  { name: "Mai Idris Alooma Polytechnic, Geidam", nickname: "MIAP", type: "Polytechnic", state: "Yobe" },
  { name: "Igbajo Polytechnic, Igbajo", nickname: "IGBAJO POLY", type: "Polytechnic", state: "Osun" },
  { name: "Ronik Polytechnic, Ikeja", nickname: "RONIK", type: "Polytechnic", state: "Lagos" },
  { name: "Lagos City Polytechnic, Ikeja", nickname: "Lagos City Poly", type: "Polytechnic", state: "Lagos" },
  { name: "Wolex Polytechnic, Ikeja", nickname: "WOLEX", type: "Polytechnic", state: "Lagos" },
  { name: "The Oke-Ogun Polytechnic, Saki", nickname: "TOPS / Oke-Ogun Poly", type: "Polytechnic", state: "Oyo" },
  { name: "Ibadan City Polytechnic, Ibadan", nickname: "ICP", type: "Polytechnic", state: "Oyo" },
  { name: "Coastal Polytechnic, Apapa", nickname: "CoastalPoly", type: "Polytechnic", state: "Lagos" },
  { name: "Grace Polytechnic, Lagos", nickname: "GracePoly", type: "Polytechnic", state: "Lagos" },
  { name: "The Polytechnic, Imesi-Ile", nickname: "Poly Imesi", type: "Polytechnic", state: "Osun" },
  { name: "The Polytechnic, Iresi", nickname: "Poly Iresi", type: "Polytechnic", state: "Osun" },
  { name: "Umaru Ali Shinkafi Polytechnic, Sokoto", nickname: "UASPOLY", type: "Polytechnic", state: "Sokoto" },
  { name: "Southern Atlantic Polytechnic, Uyo", nickname: "SAP Uyo", type: "Polytechnic", state: "Akwa Ibom" },

  // ─── FEDERAL COLLEGES OF EDUCATION ──────────────────────────────────────────
  { name: "Federal College of Education, Abeokuta", nickname: "FCE Abeokuta", type: "College", state: "Ogun" },
  { name: "Federal College of Education, Kano", nickname: "FCE Kano", type: "College", state: "Kano" },
  { name: "Federal College of Education, Katsina", nickname: "FCE Katsina", type: "College", state: "Katsina" },
  { name: "Federal College of Education, Obudu", nickname: "FCE Obudu", type: "College", state: "Cross River" },
  { name: "Federal College of Education, Okene", nickname: "FCE Okene", type: "College", state: "Kogi" },
  { name: "Federal College of Education, Pankshin", nickname: "FCE Pankshin", type: "College", state: "Plateau" },
  { name: "Federal College of Education, Yola", nickname: "FCE Yola", type: "College", state: "Adamawa" },
  { name: "Federal College of Education, Zaria", nickname: "FCE Zaria", type: "College", state: "Kaduna" },
  { name: "Federal College of Education (Tech), Akoka", nickname: "FCET Akoka", type: "College", state: "Lagos" },
  { name: "Federal College of Education (Tech), Asaba", nickname: "FCET Asaba", type: "College", state: "Delta" },
  { name: "Federal College of Education (Tech), Bichi", nickname: "FCET Bichi", type: "College", state: "Kano" },
  { name: "Federal College of Education (Tech), Gombe", nickname: "FCET Gombe", type: "College", state: "Gombe" },
  { name: "Federal College of Education (Tech), Gusau", nickname: "FCET Gusau", type: "College", state: "Zamfara" },
  { name: "Federal College of Education (Tech), Omoku", nickname: "FCET Omoku", type: "College", state: "Rivers" },
  { name: "Federal College of Education (Tech), Potiskum", nickname: "FCET Potiskum", type: "College", state: "Yobe" },
  { name: "Federal College of Education (Tech), Umunze", nickname: "FCET Umunze", type: "College", state: "Anambra" },
  { name: "Federal College of Education (Special), Oyo", nickname: "FCE Special Oyo", type: "College", state: "Oyo" },
  { name: "Federal College of Education, Eha-Amufu", nickname: "FCE Eha-Amufu", type: "College", state: "Enugu" },
  { name: "Federal College of Education, Ekiadolor", nickname: "FCE Ekiadolor", type: "College", state: "Edo" },
  { name: "Federal College of Education, Ilawe Ekiti", nickname: "FCE Ilawe", type: "College", state: "Ekiti" },
  { name: "Federal College of Education, Iwo", nickname: "FCE Iwo", type: "College", state: "Osun" },
  { name: "Federal College of Education, Kontagora", nickname: "FCE Kontagora", type: "College", state: "Niger" },
  { name: "Federal College of Agriculture, Abeokuta", nickname: "FECA Moor Plantation", type: "College", state: "Ogun" },
  { name: "Federal College of Agriculture, Akure", nickname: "FECA Akure", type: "College", state: "Ondo" },
  { name: "Federal College of Forestry, Jos", nickname: "FCF Jos", type: "College", state: "Plateau" },
  { name: "Federal College of Medical Laboratory Science and Technology, Jos", nickname: "FCMLST Jos", type: "College", state: "Plateau" },
  { name: "Federal College of Dental Technology and Therapy, Enugu", nickname: "FCDTT Enugu", type: "College", state: "Enugu" },
  { name: "Federal College of Fisheries and Marine Technology, Victoria Island", nickname: "FCFMT", type: "College", state: "Lagos" },
  { name: "Federal College of Freshwater Fisheries Technology, New Bussa", nickname: "FCFFT New Bussa", type: "College", state: "Niger" },
  { name: "Federal College of Land Resources Technology, Jos", nickname: "FCLRT Jos", type: "College", state: "Plateau" },
  { name: "Federal College of Wildlife Management, New Bussa", nickname: "FCWM", type: "College", state: "Niger" },
  { name: "Federal College of Veterinary and Medical Laboratory Tech, Vom", nickname: "FCVMLT Vom", type: "College", state: "Plateau" },

  // ─── STATE COLLEGES ──────────────────────────────────────────────────────────
  { name: "Adeniran Ogunsanya College of Education, Ijanikin", nickname: "AOCOED", type: "College", state: "Lagos" },
  { name: "Adeyemi College of Education, Ondo", nickname: "ADECOED / ACE Ondo", type: "College", state: "Ondo" },
  { name: "Akwa-Ibom State College of Education, Afaha-Nsit", nickname: "AKSCOED", type: "College", state: "Akwa Ibom" },
  { name: "Emmanuel Alayande College of Education, Oyo", nickname: "EACOED", type: "College", state: "Oyo" },
  { name: "FCT College of Education, Zuba", nickname: "FCT COE Zuba", type: "College", state: "FCT" },
  { name: "Alvan Ikoku College of Education, Owerri", nickname: "AICE Owerri", type: "College", state: "Imo" },
  { name: "College of Education, Hong", nickname: "COE Hong", type: "College", state: "Adamawa" },
  { name: "College of Education, Gindiri", nickname: "COE Gindiri", type: "College", state: "Plateau" },
  { name: "College of Education, Zing", nickname: "COE Zing", type: "College", state: "Taraba" },
  { name: "College of Education, Ikere Ekiti", nickname: "COE Ikere", type: "College", state: "Ekiti" },
  { name: "College of Education, Warri", nickname: "COE Warri", type: "College", state: "Delta" },
  { name: "College of Education, Agbor", nickname: "COE Agbor", type: "College", state: "Delta" },
  { name: "College of Education, Katsina-Ala", nickname: "COE Katsina-Ala", type: "College", state: "Benue" },
  { name: "College of Education, Minna", nickname: "COE Minna", type: "College", state: "Niger" },
  { name: "College of Education, Ankpa", nickname: "COE Ankpa", type: "College", state: "Kogi" },
  { name: "College of Education, Akwanga", nickname: "COE Akwanga", type: "College", state: "Nasarawa" },
  { name: "College of Education, Azare", nickname: "COE Azare", type: "College", state: "Bauchi" },
  { name: "College of Education, Oju", nickname: "COE Oju", type: "College", state: "Benue" },
  { name: "Tai Solarin College of Education, Ijebu-Ode", nickname: "TASCE", type: "College", state: "Ogun" },
  { name: "Michael Otedola College of Primary Education, Epe", nickname: "MOCPED", type: "College", state: "Lagos" },
  { name: "Lagos State College of Health Technology, Yaba", nickname: "LCHT Yaba", type: "College", state: "Lagos" },
  { name: "Yaba College of Technology, Yaba", nickname: "YABATECH", type: "College", state: "Lagos" },
  { name: "Kwara State College of Education, Ilorin", nickname: "KWACOED Ilorin", type: "College", state: "Kwara" },
  { name: "Kaduna State College of Education, Gidan-Waya", nickname: "KDCOED", type: "College", state: "Kaduna" },
  { name: "Niger State College of Education, Minna", nickname: "NSCOED Minna", type: "College", state: "Niger" },
  { name: "Ebonyi State College of Education, Ikwo", nickname: "EBCOED", type: "College", state: "Ebonyi" },
  { name: "Osun State College of Education, Ila-Orangun", nickname: "OSCOED Ila", type: "College", state: "Osun" },
  { name: "Osun State College of Education, Ilesa", nickname: "OSCOED Ilesa", type: "College", state: "Osun" },
  { name: "Cross River State College of Education, Akamkpa", nickname: "CRSCED", type: "College", state: "Cross River" },
  { name: "Enugu State College of Education (Technical)", nickname: "ESCET Enugu", type: "College", state: "Enugu" },
  { name: "Kogi State College of Education (Technical), Kabba", nickname: "KSCET Kabba", type: "College", state: "Kogi" },
  { name: "FCT College of Nursing, Gwagwalada", nickname: "FCT Nursing Gwagwalada", type: "College", state: "FCT" },
  { name: "Isaac Jasper Boro College of Education, Sagbama", nickname: "IJBCOE", type: "College", state: "Bayelsa" },
  { name: "Jibwis College of Education, Gombe", nickname: "JIBWIS COE Gombe", type: "College", state: "Gombe" },
  { name: "Kashim-Ibrahim College of Education, Maiduguri", nickname: "KICE Maiduguri", type: "College", state: "Borno" },
  { name: "Nwafor Orizu College of Education, Nsugbe", nickname: "NOCEN", type: "College", state: "Anambra" },
  { name: "Saadatu Rimi College of Education, Kumbotso", nickname: "SRCE Kano", type: "College", state: "Kano" },
  { name: "Shehu Shagari College of Education, Sokoto", nickname: "SSCE Sokoto", type: "College", state: "Sokoto" },
  { name: "Aminu Kano College of Education, Kano", nickname: "AKCE Kano", type: "College", state: "Kano" },
  { name: "Isa Kaita College of Education, Dutsinma", nickname: "IKCE Dutsinma", type: "College", state: "Katsina" },
  { name: "Peaceland College of Education, Enugu", nickname: "PEACE COE Enugu", type: "College", state: "Enugu" },
  { name: "College of Education, Ilesha", nickname: "COE Ilesha", type: "College", state: "Osun" },
  { name: "College of Nursing Sciences, OAU Teaching Hospital, Ile-Ife", nickname: "OAUTH Nursing", type: "College", state: "Osun" },
  { name: "College of Nursing Sciences, NAUTH, Nnewi", nickname: "NAUTH Nursing", type: "College", state: "Anambra" },
  { name: "College of Nursing Sciences, UNTH, Enugu", nickname: "UNTH Nursing", type: "College", state: "Enugu" },
  { name: "Samaru College of Agriculture, Zaria", nickname: "SCA Zaria / Samaru", type: "College", state: "Kaduna" },
  { name: "ECWA College of Education, Igbaja", nickname: "ECWA COE Igbaja", type: "College", state: "Kwara" },
  { name: "ECWA College of Education, Jos", nickname: "ECWA COE Jos", type: "College", state: "Plateau" },
];

// ─── SEARCH FUNCTION ──────────────────────────────────────────────────────────
// Finds institutions by name or nickname, max 8 results
export function searchInstitutions(query) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase().trim();
  
  // Score matches: nickname match = higher priority, name match = lower
  const results = INSTITUTIONS
    .map(inst => {
      const nicknameMatch = inst.nickname.toLowerCase().includes(q);
      const nameMatch = inst.name.toLowerCase().includes(q);
      const exactNickname = inst.nickname.toLowerCase() === q;
      
      if (!nicknameMatch && !nameMatch) return null;
      
      let score = 0;
      if (exactNickname) score = 100;
      else if (inst.nickname.toLowerCase().startsWith(q)) score = 80;
      else if (nicknameMatch) score = 60;
      else if (inst.name.toLowerCase().startsWith(q)) score = 40;
      else score = 20;
      
      return { ...inst, score };
    })
    .filter(Boolean)
    .sort((a, b) => b.score - a.score)
    .slice(0, 8);
  
  return results;
}

// Get display label: shows nickname + state
export function getInstitutionLabel(inst) {
  return `${inst.nickname} — ${inst.state}`;
}

export default INSTITUTIONS;
